from enum import StrEnum


class ErrorCode(StrEnum):
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
    KEY_NOT_FOUND = "KEY_NOT_FOUND"
    REFRESH_TOKEN_MISSMATCH = "REFRESH_TOKEN_MISSMATCH"
    TOKEN_NOT_PROVIDED = "TOKEN_NOT_PROVIDED"
    INVALID_TOKEN = "INVALID_TOKEN"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    GAME_NOT_FOUND = "GAME_NOT_FOUND"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    WORDS_NOT_FOUND = "WORDS_NOT_FOUND"
    NOT_A_PARTICIPANT = "NOT_A_PARTICIPANT"
    VALIDATION_ERROR = "VALIDATION_ERROR"


class CookieNames(StrEnum):
    ACCESS_TOKEN = "TP_AT"
    REFRESH_TOKEN = "TP_RT"
    USERNAME = "USERNAME"


class WSCloseReason(StrEnum):
    INVALID_TOKEN = "INVALID_TOKEN"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    ACCESS_TOKEN_NOT_FOUND = "ACCESS_TOKEN_NOT_FOUND"
    GAME_NOT_FOUND = "GAME_NOT_FOUND"
    NOT_A_PARTICIPANT = "NOT_A_PARTICIPANT"


class UserType(StrEnum):
    GUEST = "GUEST"
    REGISTERED = "REGISTERED"


class QueueInType(StrEnum):
    RECONNECT = "reconnect"
    NEW = "new"
